package io.mosip.ivv.orchestrator;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Base64;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Properties;

import javax.ws.rs.core.MediaType;

import org.testng.Reporter;

import io.mosip.admin.fw.util.AdminTestUtil;
import io.mosip.admin.fw.util.TestCaseDTO;
import io.mosip.authentication.fw.util.RestClient;
import io.mosip.ivv.core.base.BaseStep;
import io.mosip.service.BaseTestCase;
import io.restassured.response.Response;

public class BaseTestCaseUtil extends BaseStep{
	public static HashMap<String, String> pridsAndRids=new LinkedHashMap<String, String>();
	public static HashMap<String, String> uinReqIds = new LinkedHashMap<String, String>();
	public static Properties props = new AdminTestUtil().getproperty(TestResources.getGlobalResourcePaths()+"/config/test-orchestrator_mz.properties");
	public String baseUrl=props.getProperty("packetUtilityBaseUrl");
	public static HashMap<String, String> residentTemplatePaths = new LinkedHashMap<String, String>();
	public static HashMap<String, String> residentPathsPrid = new LinkedHashMap<String, String>();
	public static HashMap<String, String> templatePacketPath = new LinkedHashMap<String, String>();
	public static HashMap<String, String> residentPathGuardianRid = null;
	public static final long DEFAULT_WAIT_TIME = 30000l;
	public static final long TIME_IN_MILLISEC = 1000l;
	public static String prid=null;
	public static PacketUtility packetUtility= new PacketUtility();
	public BaseTestCaseUtil() {}
	
	public String encoder(String text) {
		return Base64.getEncoder().encodeToString(text.getBytes());
	}
	
	public String readProperty() {
		String preRegistrationId=null;
		FileInputStream inputStrem = null;
		Properties props = new Properties();
		try {
			inputStrem = new FileInputStream(TestResources.getResourcePath() + "preReg/autoGeneratedId.properties");
			props.load(inputStrem);
			preRegistrationId=props.getProperty("CreatePrereg_All_Valid_Smoke_sid_preRegistrationId");
		} catch (IOException e) {
			e.printStackTrace();
		}
		return preRegistrationId;
	}
	
	public Object[] filterTestCases(Object[] testCases) {
		String testlable = BaseTestCase.testLevel;
		 List<Object> filteredCases = new ArrayList<>();
		 if(testlable.equalsIgnoreCase("smoke")) {
		 for (Object object : testCases)
		 {
			 TestCaseDTO test = (TestCaseDTO) object;
			 if(test.getTestCaseName().toLowerCase().contains(testlable.toLowerCase()))
				 filteredCases.add(object);
		 }
		return filteredCases.toArray();
	}
		 return testCases;
	}
	
	public Response postReqest(String url,String body,String opsToLog) {
		Reporter.log("<pre> <b>"+opsToLog+": </b> <br/>"+body + "</pre>");
		Response apiResponse = RestClient.postRequest(url, body, MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON);
		Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"+ apiResponse.getBody().asString() + "</pre>");
		return apiResponse;
	}
	
}
