package io.mosip.ivv.e2e.constant;

public enum EventTrigger {
	SEND_OTP, 
	VERIFY_OTP, 
	ADD_APPLICATION, 
	UPLOAD_DOCUMENTS, 
	BOOK_APPOINTMENT, 
	REGISTER_PACKET, 
	GET_TEMPLATE,
	CREATE_PACKET, 
	RIDSYNC
}
