# ===== PRID =====
mosip.kernel.prid.length=14
mosip.kernel.prid.sequence-limit=3
mosip.kernel.prid.repeating-block-limit=3
mosip.kernel.prid.repeating-limit=2
mosip.kernel.prid.not-start-with=0,1
mosip.kernel.prid.restricted-numbers=786,666

# ===== VID =====
mosip.kernel.vid.length=16
mosip.kernel.vid.length.sequence-limit=3
mosip.kernel.vid.length.repeating-block-limit=2
mosip.kernel.vid.length.repeating-limit=2
mosip.kernel.vid.not-start-with=0,1
mosip.kernel.vid.restricted-numbers=786,666

# ===== UIN =====
mosip.kernel.uin.length=10
mosip.kernel.uin.length.sequence-limit=3
mosip.kernel.uin.length.repeating-block-limit=2
mosip.kernel.uin.length.repeating-limit=2
mosip.kernel.uin.length.reverse-digits-limit=5
mosip.kernel.uin.length.digits-limit=5
mosip.kernel.uin.length.conjugative-even-digits-limit=3
mosip.kernel.uin.not-start-with=0,1
mosip.kernel.uin.restricted-numbers=786,666