apiVersion: v2
name: uitestrig
description: A Helm chart to deploy uitestrig to test working of MOSIP modules
type: application
version: 0.0.1-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - uitestrig
  - testrig
maintainers:
  - email: info@mosip.io
    name: MOSIP
