# This is a basic workflow that is manually triggered

name: Manual test workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      env:
        description: 'environment to run on'
        default: 'dev'
        required: true
      baseUrl:
        description: 'base url'
        default: 'dev.mosip.net'
        required: true
      modules:
        description: 'modules to run'
        default: 'kernel'
        required: true
      testLevel:
        description: 'tests to run'
        default: 'smokeAndRegression'
        required: true
         
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        ref: ${{ github.ref }}
        java-version: 1.8
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Maven
      run: |
        cd automationtests
        mvn -B package -s $GITHUB_WORKSPACE/settings.xml --file pom.xml
    - name: Trigger automation run
      run:
        java -Dmaven.test.failure.ignore=true -Dmaven.test.failure.ignore=true -Denv.user=${{github.event.inputs.env}} -Denv.endpoint=https://${{github.event.inputs.baseUrl}} -Denv.testLevel=${{github.event.inputs.testLevel}} -DuserID=110022 -Dmodules=${{github.event.inputs.modules}} -jar ./target/automationtests-1.0.10-jar-with-dependencies.jar"
        
