package io.mosip.admin.fw.util;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.lang.reflect.Type;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.Base64;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.Set;
import java.util.TimeZone;
import java.util.stream.Collectors;

import javax.ws.rs.core.MediaType;

import org.apache.commons.io.FileUtils;
import org.apache.commons.lang3.StringUtils;
import org.apache.log4j.Logger;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import org.testng.Reporter;
import org.yaml.snakeyaml.Yaml;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.github.jknack.handlebars.Context;
import com.github.jknack.handlebars.Handlebars;
import com.github.jknack.handlebars.Template;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

import au.com.bytecode.opencsv.CSVReader;
import au.com.bytecode.opencsv.CSVWriter;
import io.mosip.authentication.fw.precon.JsonPrecondtion;
import io.mosip.authentication.fw.precon.MessagePrecondtion;
import io.mosip.authentication.fw.util.FileUtil;
import io.mosip.authentication.fw.util.ReportUtil;
import io.mosip.authentication.fw.util.RestClient;
import io.mosip.authentication.fw.util.RunConfigUtil;
import io.mosip.kernel.util.KernelDataBaseAccess;
import io.mosip.service.BaseTestCase;
import io.mosip.testrunner.MosipTestRunner;
import io.restassured.response.Response;


/**
 * @author Ravi Kant
 *
 */
public class AdminTestUtil extends BaseTestCase{
	
	private static final Logger logger = Logger.getLogger(AdminTestUtil.class);
	static KernelDataBaseAccess masterDB = new KernelDataBaseAccess();
	String token = null;
	String adminAutoGeneratedIdPropFileName = "/admin/autoGeneratedId.properties";
	String preregAutoGeneratedIdPropFileName = "/preReg/autoGeneratedId.properties";
	String partnerAutoGeneratedIdPropFileName = "/partner/autoGeneratedId.properties";
	String idrepoAutoGeneratedIdPropFileName = "/idRepository/autoGeneratedId.properties";
	String residentAutoGeneratedIdPropFileName = "/resident/autoGeneratedId.properties";
	String authAutoGeneratedIdPropFileName = "/ida/autoGeneratedId.properties";
	String regProcAutoGeneratedIdPropFileName = "/regProc/autoGeneratedId.properties";
	public static final String resourceFolderName="MosipTemporaryTestResource";
	public static String genertedUIN=null;
	public static String generatedRid=null;
	public static String regDeviceResponse=null;
	public static String generatedVID=null;
	public static final String AUTHORIZATHION_HEADERNAME="Authorization";
	public static final String authHeaderValue="Some String";
	public static final String SIGNATURE_HEADERNAME="signature";
	public static Properties props = getproperty(MosipTestRunner.getGlobalResourcePath() + "/"+"config/application.properties");
	public static BioDataUtility bioDataUtil = new BioDataUtility();
	public static EncryptionDecrptionUtil encryptDecryptUtil = new EncryptionDecrptionUtil();
	
	
	/**
	 * This method will hit post request and return the response
	 * @param url
	 * @param jsonInput
	 * @param cookieName
	 * @param role
	 * @return Response
	 */
	protected Response postWithBodyAndCookie(String url, String jsonInput, String cookieName, String role, String testCaseName) {
		Response response=null;
		String inputJson = inputJsonKeyWordHandeler(jsonInput, testCaseName);
		token = kernelAuthLib.getTokenByRole(role);
		logger.info("******Post request Json to EndPointUrl: " + url + " *******");
		Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(inputJson) + "</pre>");
		try {
			  response = RestClient.postRequestWithCookie(url, inputJson, MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON, cookieName, token);
			  Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"
						+ ReportUtil.getTextAreaJsonMsgHtml(response.asString()) + "</pre>");
			return response;
		} catch (Exception e) {
			logger.error("Exception " + e);
			return response;
		}
	}
	
	protected Response postRequestWithCookieAuthHeaderAndSignature(String url, String jsonInput, String cookieName, String role, String testCaseName) {
		Response response=null;
		HashMap<String, String> headers = new HashMap<String, String>();
		headers.put(AUTHORIZATHION_HEADERNAME, authHeaderValue);
		String inputJson = inputJsonKeyWordHandeler(jsonInput, testCaseName);
		headers.put( SIGNATURE_HEADERNAME, generateSignatureWithRequest(inputJson, null));
		token = kernelAuthLib.getTokenByRole(role);
		logger.info("******Post request Json to EndPointUrl: " + url + " *******");
		Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(inputJson) + "</pre>");
		try {
			  response = RestClient.postRequestWithMultipleHeaders(url, inputJson, MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON, cookieName, token, headers);
			  Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"
						+ ReportUtil.getTextAreaJsonMsgHtml(response.asString()) + "</pre>");
			return response;
		} catch (Exception e) {
			logger.error("Exception " + e);
			return response;
		}
	}
	
	protected Response patchRequestWithCookieAuthHeaderAndSignature(String url, String jsonInput, String cookieName, String role, String testCaseName) {
		Response response=null;
		HashMap<String, String> headers = new HashMap<String, String>();
		headers.put(AUTHORIZATHION_HEADERNAME, authHeaderValue);
		String inputJson = inputJsonKeyWordHandeler(jsonInput, testCaseName);
		headers.put( SIGNATURE_HEADERNAME, generateSignatureWithRequest(inputJson, null));
		token = kernelAuthLib.getTokenByRole(role);
		logger.info("******Patch request Json to EndPointUrl: " + url + " *******");
		Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(inputJson) + "</pre>");
		try {
			  response = RestClient.patchRequestWithMultipleHeaders(url, inputJson, MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON, cookieName, token, headers);
			  Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"
						+ ReportUtil.getTextAreaJsonMsgHtml(response.asString()) + "</pre>");
			return response;
		} catch (Exception e) {
			logger.error("Exception " + e);
			return response;
		}
	}
	protected Response postRequestWithAuthHeaderAndSignature(String url, String jsonInput, String testCaseName) {
		Response response=null;
		HashMap<String, String> headers = new HashMap<String, String>();
		headers.put(AUTHORIZATHION_HEADERNAME, authHeaderValue);
		String inputJson = inputJsonKeyWordHandeler(jsonInput, testCaseName);
		headers.put( SIGNATURE_HEADERNAME, generateSignatureWithRequest(inputJson, null));
		logger.info("******Post request Json to EndPointUrl: " + url + " *******");
		Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(inputJson) + "</pre>");
		try {
			  response = RestClient.postRequestWithMultipleHeadersWithoutCookie(url, inputJson, MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON, headers);
			  Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"
						+ ReportUtil.getTextAreaJsonMsgHtml(response.asString()) + "</pre>");
			return response;
		} catch (Exception e) {
			logger.error("Exception " + e);
			return response;
		}
	}
	
	protected Response postRequestWithCookieAndHeader(String url, String jsonInput, String cookieName, String role, String testCaseName) {
		Response response=null;
		String inputJson = inputJsonKeyWordHandeler(jsonInput, testCaseName);
		token = kernelAuthLib.getTokenByRole(role);
		logger.info("******Post request Json to EndPointUrl: " + url + " *******");
		Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(inputJson) + "</pre>");
		try {
			  response = RestClient.postRequestWithCookieAndHeader(url, inputJson, MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON, cookieName, token, AUTHORIZATHION_HEADERNAME, authHeaderValue);
			  Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"
						+ ReportUtil.getTextAreaJsonMsgHtml(response.asString()) + "</pre>");
			return response;
		} catch (Exception e) {
			logger.error("Exception " + e);
			return response;
		}
	}
	
	protected Response patchRequestWithCookieAndHeader(String url, String jsonInput, String cookieName, String role, String testCaseName) {
		Response response=null;
		if(url.contains("ID:"))
			url = inputJsonKeyWordHandeler(url, testCaseName );
		String inputJson = inputJsonKeyWordHandeler(jsonInput, testCaseName);
		token = kernelAuthLib.getTokenByRole(role);
		logger.info("******Post request Json to EndPointUrl: " + url + " *******");
		Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(inputJson) + "</pre>");
		try {
			  response = RestClient.patchRequestWithCookieAndHeader(url, inputJson, MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON, cookieName, token, AUTHORIZATHION_HEADERNAME, authHeaderValue);
			  Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"
						+ ReportUtil.getTextAreaJsonMsgHtml(response.asString()) + "</pre>");
			return response;
		} catch (Exception e) {
			logger.error("Exception " + e);
			return response;
		}
	}
	
	protected Response patchWithBodyAndCookie(String url, String jsonInput, String cookieName, String role, String testCaseName) {
		Response response=null;
		String inputJson = inputJsonKeyWordHandeler(jsonInput, testCaseName);
		token = kernelAuthLib.getTokenByRole(role);
		logger.info("******Post request Json to EndPointUrl: " + url + " *******");
		Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(inputJson) + "</pre>");
		try {
			  response = RestClient.patchRequestWithCookie(url, inputJson, MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON, cookieName, token);
			  Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"
						+ ReportUtil.getTextAreaJsonMsgHtml(response.asString()) + "</pre>");
			return response;
		} catch (Exception e) {
			logger.error("Exception " + e);
			return response;
		}
	}
	
	protected Response postWithBodyAndCookieForAutoGeneratedId(String url, String jsonInput, String cookieName, String role, String testCaseName, String idKeyName) {
		Response response=null;
		String inputJson = inputJsonKeyWordHandeler(jsonInput, testCaseName);
		token = kernelAuthLib.getTokenByRole(role);
		logger.info("******Post request Json to EndPointUrl: " + url + " *******");
		Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(inputJson) + "</pre>");
		try {
			  response = RestClient.postRequestWithCookie(url, inputJson, MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON, cookieName, token);
			  Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"
						+ ReportUtil.getTextAreaJsonMsgHtml(response.asString()) + "</pre>");
			  
			  if(testCaseName.toLowerCase().contains("_sid"))
			  {
				  writeAutoGeneratedId(response, idKeyName, testCaseName);
			  }
				  
			return response;
		} catch (Exception e) {
			logger.error("Exception " + e);
			return response;
		}
	}
	
	protected Response patchWithBodyAndCookieForAutoGeneratedId(String url, String jsonInput, String cookieName, String role, String testCaseName, String idKeyName) {
		Response response=null;
		String inputJson = inputJsonKeyWordHandeler(jsonInput, testCaseName);
		token = kernelAuthLib.getTokenByRole(role);
		logger.info("******Post request Json to EndPointUrl: " + url + " *******");
		Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(inputJson) + "</pre>");
		try {
			  response = RestClient.patchRequestWithCookie(url, inputJson, MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON, cookieName, token);
			  Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"
						+ ReportUtil.getTextAreaJsonMsgHtml(response.asString()) + "</pre>");
			  
			  if(testCaseName.toLowerCase().contains("_sid"))
			  {
				  writeAutoGeneratedId(response, idKeyName, testCaseName);
			  }
				  
			return response;
		} catch (Exception e) {
			logger.error("Exception " + e);
			return response;
		}
	}
	
	protected Response postWithFormPathParamAndFile(String url, String jsonInput, String cookieName, String role, String testCaseName, String idKeyName) {
		Response response=null;
		String inputJson = inputJsonKeyWordHandeler(jsonInput, testCaseName);
		JSONObject req = new JSONObject(inputJson);
		HashMap<String, String> formParams = new HashMap<String, String>();
		HashMap<String, String> pathParams = new HashMap<String, String>();
		
		File filetoUpload = null;
		String fileKeyName = null;
		if(req.has("filePath") && req.has("fileKeyName") ) {
		 filetoUpload = new File(getResourcePath() + req.get("filePath").toString());
		 req.remove("filePath");
		 fileKeyName = req.get("fileKeyName").toString();
		 req.remove("fileKeyName");
		}
		else 
			logger.error("request doesn't contanin filePath and fileKeyName: "+inputJson);
		pathParams.put("preRegistrationId", req.get("preRegistrationId").toString());
		req.remove("preRegistrationId");
		formParams.put("Document request", req.toString());
		token = kernelAuthLib.getTokenByRole(role);
		logger.info("******Post request Json to EndPointUrl: " + url + " *******");
		Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(inputJson) + "</pre>");
		try {
			response = RestClient.postWithFormPathParamAndFile(url, formParams, pathParams, filetoUpload, fileKeyName,
						MediaType.MULTIPART_FORM_DATA, token);
			  Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"
						+ ReportUtil.getTextAreaJsonMsgHtml(response.asString()) + "</pre>");
			  
			  if(testCaseName.toLowerCase().contains("_sid"))
			  {
				  writeAutoGeneratedId(response, idKeyName, testCaseName);
			  }
			return response;
		} catch (Exception e) {
			logger.error("Exception " + e);
			return response;
		}
	}
	
	protected Response postWithFormDataAndFile(String url, String jsonInput, String cookieName, String role, String testCaseName,String idKeyName) {
		Response response=null;
		String inputJson = inputJsonKeyWordHandeler(jsonInput, testCaseName);

		JSONObject req = new JSONObject(inputJson);
		HashMap<String, String> formParams = new HashMap<String, String>();
		formParams.put("category", req.getString("category"));
		formParams.put("operation", req.getString("operation"));
		formParams.put("tableName", req.getString("tableName"));
		
		String absolueFilePath=null;
		JSONArray josnArray=req.getJSONArray("files");
		for(int index=0;index<josnArray.length();index++) {
			String csvFilePath=(String)josnArray.get(index);
			 absolueFilePath=getResourcePath()+csvFilePath;
		}
		 token = kernelAuthLib.getTokenByRole(role);
		logger.info("******Post request Json to EndPointUrl: " + url + " *******");
		Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(inputJson) + "</pre>");
		try {
			response = RestClient.postWithFormDataAndFile(url, formParams, absolueFilePath,
					MediaType.MULTIPART_FORM_DATA, token);
			  Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"
						+ ReportUtil.getTextAreaJsonMsgHtml(response.asString()) + "</pre>");
			  if(testCaseName.toLowerCase().contains("_sid"))
			  {
				  writeAutoGeneratedId(response, idKeyName, testCaseName);
			  }
			  
			return response;
		} catch (Exception e) {
			logger.error("Exception " + e);
			return response;
		}
	}
	
	protected Response postWithFormDataAndMultipleFile(String url, String jsonInput, String cookieName, String role, String testCaseName,String idKeyName) {
		Response response=null;
		String inputJson = inputJsonKeyWordHandeler(jsonInput, testCaseName);

		JSONObject req = new JSONObject(inputJson);
		HashMap<String, String> formParams = new HashMap<String, String>();
		formParams.put("category", req.getString("category"));
		formParams.put("operation", req.getString("operation"));
		formParams.put("tableName", req.getString("tableName"));
		
		String absolueFilePath = null;
		JSONArray josnArray = req.getJSONArray("files");
		for (int index = 0; index < josnArray.length(); index++) {
			String csvFilePath = (String) josnArray.get(index);
			absolueFilePath = getResourcePath() + csvFilePath;
			if (formParams.get("category").equals("masterData")) {
				absolueFilePath = StringUtils.substringBefore(absolueFilePath, "FilesToUpload") + "FilesToUpload";
			}
		}
		
		File file = new File(absolueFilePath);
		File[] listFiles = file.listFiles();
		for (File specificFile : listFiles) {
			if (formParams.get("operation").equalsIgnoreCase("insert")
					&& specificFile.getName().equals(formParams.get("tableName") + ".csv")) {
				specificFile=updateCSV(specificFile.getAbsolutePath(),"OLD",1,0);
				listFiles = new File[1];
				listFiles[0] = specificFile;
			} else {
				if (formParams.get("operation").equalsIgnoreCase("update")
						&& specificFile.getName().equalsIgnoreCase("update" + formParams.get("tableName") + ".csv")) {
					listFiles = new File[1];
					listFiles[0] = specificFile;
				}
			}
		}
		 token = kernelAuthLib.getTokenByRole(role);
		logger.info("******Post request Json to EndPointUrl: " + url + " *******");
		Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(inputJson) + "</pre>");
		try {
			response = RestClient.postWithFormDataAndMultipleFile(url, formParams, listFiles,
					MediaType.MULTIPART_FORM_DATA, token);
			  Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"
						+ ReportUtil.getTextAreaJsonMsgHtml(response.asString()) + "</pre>");
			  if(testCaseName.toLowerCase().contains("_sid"))
			  {
				  writeAutoGeneratedId(response, idKeyName, testCaseName);
			  }
			  
			return response;
		} catch (Exception e) {
			logger.error("Exception " + e);
			return response;
		}
	}
	
	/**
	 * This method will hit put request and return the response
	 * @param url
	 * @param jsonInput
	 * @param cookieName
	 * @param role
	 * @return Response
	 */
	protected Response putWithBodyAndCookie(String url, String jsonInput, String cookieName, String role, String testCaseName) {
		Response response=null;
		String inputJson = inputJsonKeyWordHandeler(jsonInput, testCaseName);
		token = kernelAuthLib.getTokenByRole(role);
		logger.info("******Put request Json to EndPointUrl: " + url + " *******");
		Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(inputJson) + "</pre>");
		try {
			  response = RestClient.putRequestWithCookie(url, inputJson, MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON, cookieName, token);
			  Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"
						+ ReportUtil.getTextAreaJsonMsgHtml(response.asString()) + "</pre>");
			return response;
		} catch (Exception e) {
			logger.error("Exception " + e);
			return response;
		}
	}
	
	protected Response putWithPathParamAndCookie(String url, String jsonInput, String cookieName, String role, String testCaseName) {
		Response response=null;
		String inputJson = inputJsonKeyWordHandeler(jsonInput, testCaseName);
		HashMap<String, String> map = null;
		try {
			map = new Gson().fromJson(inputJson, new TypeToken<HashMap<String, String>>(){}.getType());
		} catch (Exception e) {
			logger.error("Not able to convert jsonrequet to map: "+jsonInput+" Exception: "+e.getMessage());
		}
		token = kernelAuthLib.getTokenByRole(role);
		logger.info("******Put request Json to EndPointUrl: " + url + " *******");
		Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(inputJson) + "</pre>");
		try {
			  response = RestClient.putRequestWithParm(url, map, MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON, cookieName, token);
			  Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"
						+ ReportUtil.getTextAreaJsonMsgHtml(response.asString()) + "</pre>");
			return response;
		} catch (Exception e) {
			logger.error("Exception " + e);
			return response;
		}
	}
	
	protected Response patchWithPathParamAndCookie(String url, String jsonInput, String cookieName, String role, String testCaseName) {
		Response response=null;
		String inputJson = inputJsonKeyWordHandeler(jsonInput, testCaseName);
		HashMap<String, String> map = null;
		try {
			map = new Gson().fromJson(inputJson, new TypeToken<HashMap<String, String>>(){}.getType());
		} catch (Exception e) {
			logger.error("Not able to convert jsonrequet to map: "+inputJson+" Exception: "+e.getMessage());
		}
		token = kernelAuthLib.getTokenByRole(role);
		logger.info("******Put request Json to EndPointUrl: " + url + " *******");
		Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(inputJson) + "</pre>");
		try {
			  response = RestClient.patchRequestWithParm(url, map, MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON, cookieName, token);
			  Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"
						+ ReportUtil.getTextAreaJsonMsgHtml(response.asString()) + "</pre>");
			return response;
		} catch (Exception e) {
			logger.error("Exception " + e);
			return response;
		}
	}
	
	protected Response putWithPathParamsBodyAndCookie(String url, String jsonInput, String cookieName, String role, String testCaseName, String pathParams) {
		Response response=null;
		String inputJson = inputJsonKeyWordHandeler(jsonInput, testCaseName);
		JSONObject req = new JSONObject(inputJson);
		HashMap<String, String> pathParamsMap = new HashMap<String, String>();
		String params[] = pathParams.split(",");
		for(String param: params)
		{
			if(req.has(param)) {
				 pathParamsMap.put(param, req.get(param).toString());
				 req.remove(param);
			}
			else 
			logger.error("request doesn't contanin param: "+param+" in: "+inputJson);
		}
		
		token = kernelAuthLib.getTokenByRole(role);
		logger.info("******put request Json to EndPointUrl: " + url + " *******");
		Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(inputJson) + "</pre>");
		try {
			response = RestClient.putWithPathParamsBodyAndCookie(url, pathParamsMap, req.toString(), MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON, cookieName, token);
			  Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"
						+ ReportUtil.getTextAreaJsonMsgHtml(response.asString()) + "</pre>");
			return response;
		} catch (Exception e) {
			logger.error("Exception " + e);
			return response;
		}
	}
	protected Response postWithPathParamsBodyAndCookie(String url, String jsonInput, String cookieName, String role, String testCaseName, String pathParams) {
		Response response=null;
		String inputJson = inputJsonKeyWordHandeler(jsonInput, testCaseName);
		JSONObject req = new JSONObject(inputJson);
		HashMap<String, String> pathParamsMap = new HashMap<String, String>();
		String params[] = pathParams.split(",");
		for(String param: params)
		{
			if(req.has(param)) {
				 pathParamsMap.put(param, req.get(param).toString());
				 req.remove(param);
			}
			else 
			logger.error("request doesn't contanin param: "+param+" in: "+inputJson);
		}
		
		token = kernelAuthLib.getTokenByRole(role);
		logger.info("******put request Json to EndPointUrl: " + url + " *******");
		Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(inputJson) + "</pre>");
		try {
			response = RestClient.postWithPathParamsBodyAndCookie(url, pathParamsMap, req.toString(), MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON, cookieName, token);
			  Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"
						+ ReportUtil.getTextAreaJsonMsgHtml(response.asString()) + "</pre>");
			return response;
		} catch (Exception e) {
			logger.error("Exception " + e);
			return response;
		}
	}
	
	
	protected Response patchWithPathParamsBodyAndCookie(String url, String jsonInput, String cookieName, String role, String testCaseName, String pathParams) {
		Response response=null;
		String inputJson = inputJsonKeyWordHandeler(jsonInput, testCaseName);
		JSONObject req = new JSONObject(inputJson);
		HashMap<String, String> pathParamsMap = new HashMap<String, String>();
		String params[] = pathParams.split(",");
		for(String param: params)
		{
			if(req.has(param)) {
				 pathParamsMap.put(param, req.get(param).toString());
				 req.remove(param);
			}
			else 
			logger.error("request doesn't contanin param: "+param+" in: "+inputJson);
		}
		
		token = kernelAuthLib.getTokenByRole(role);
		logger.info("******put request Json to EndPointUrl: " + url + " *******");
		Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(req.toString()) + "</pre>");
		try {
			response = RestClient.patchWithPathParamsBodyAndCookie(url, pathParamsMap, req.toString(), MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON, cookieName, token);
			  Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"
						+ ReportUtil.getTextAreaJsonMsgHtml(response.asString()) + "</pre>");
			return response;
		} catch (Exception e) {
			logger.error("Exception " + e);
			return response;
		}
	}
	
	/**
	 * This method will hit get request and return the response
	 * @param url
	 * @param jsonInput
	 * @param cookieName
	 * @param role
	 * @return Response
	 */
	protected Response getWithPathParamAndCookie(String url, String jsonInput, String cookieName, String role, String testCaseName) {
			Response response=null;
			jsonInput = inputJsonKeyWordHandeler(jsonInput, testCaseName);
			HashMap<String, String> map = null;
			try {
				map = new Gson().fromJson(jsonInput, new TypeToken<HashMap<String, String>>(){}.getType());
			} catch (Exception e) {
				logger.error("Not able to convert jsonrequet to map: "+jsonInput+" Exception: "+e.getMessage());
			}
		
		token = kernelAuthLib.getTokenByRole(role);
		logger.info("******get request to EndPointUrl: " + url + " *******");
		Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(jsonInput) + "</pre>");
		try {
			
			response = RestClient.getRequestWithCookieAndPathParm(url, map, MediaType.APPLICATION_JSON,
					MediaType.APPLICATION_JSON, cookieName, token);
			Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"
					+ ReportUtil.getTextAreaJsonMsgHtml(response.asString()) + "</pre>");
			return response;
			 
		} catch (Exception e) {
			logger.error("Exception " + e);
			return response;
		}
	}
	
	protected Response deleteWithPathParamAndCookie(String url, String jsonInput, String cookieName, String role, String testCaseName) {
		Response response=null;
		jsonInput = inputJsonKeyWordHandeler(jsonInput, testCaseName);
		HashMap<String, String> map = null;
		try {
			map = new Gson().fromJson(jsonInput, new TypeToken<HashMap<String, String>>(){}.getType());
		} catch (Exception e) {
			logger.error("Not able to convert jsonrequet to map: "+jsonInput+" Exception: "+e.getMessage());
		}
	
	token = kernelAuthLib.getTokenByRole(role);
	logger.info("******get request to EndPointUrl: " + url + " *******");
	Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(jsonInput) + "</pre>");
	try {
		
		response = RestClient.deleteRequestWithCookieAndPathParm(url, map, MediaType.APPLICATION_JSON,
				MediaType.APPLICATION_JSON, cookieName, token);
		Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"
				+ ReportUtil.getTextAreaJsonMsgHtml(response.asString()) + "</pre>");
		return response;
		 
	} catch (Exception e) {
		logger.error("Exception " + e);
		return response;
	}
}
	
	protected byte[] getWithPathParamAndCookieForPdf(String url, String jsonInput, String cookieName, String role, String testCaseName) {
		byte[] pdf=null;
		jsonInput = inputJsonKeyWordHandeler(jsonInput, testCaseName);
		HashMap<String, String> map = null;
		try {
			map = new Gson().fromJson(jsonInput, new TypeToken<HashMap<String, String>>(){}.getType());
		} catch (Exception e) {
			logger.error("Not able to convert jsonrequet to map: "+jsonInput+" Exception: "+e.getMessage());
		}
	
	token = kernelAuthLib.getTokenByRole(role);
	logger.info("******get request to EndPointUrl: " + url + " *******");
	Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(jsonInput) + "</pre>");
	try {
		pdf=RestClient.getPdf(url, map, MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON, cookieName, token);
		return pdf;
	} catch (Exception e) {
		logger.error("Exception " + e);
		return pdf;
	}
}
	
	
	protected Response getWithQueryParamAndCookie(String url, String jsonInput, String cookieName, String role, String testCaseName) {
		Response response=null;
		jsonInput = inputJsonKeyWordHandeler(jsonInput, testCaseName);
		HashMap<String, String> map = null;
		try {
			map = new Gson().fromJson(jsonInput, new TypeToken<HashMap<String, String>>(){}.getType());
		} catch (Exception e) {
			logger.error("Not able to convert jsonrequet to map: "+jsonInput+" Exception: "+e.getMessage());
		}
	
	token = kernelAuthLib.getTokenByRole(role);
	logger.info("******get request to EndPointUrl: " + url + " *******");
	Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(jsonInput) + "</pre>");
	try {
		  response = RestClient.getRequestWithCookieAndQueryParm(url, map, MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON, cookieName, token);
		  Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"
					+ ReportUtil.getTextAreaJsonMsgHtml(response.asString()) + "</pre>");
		return response;
	} catch (Exception e) {
		logger.error("Exception " + e.getMessage());
		return response;
	}
}
	
	void writeAutoGeneratedId(Response response, String idKeyName, String testCaseName)
	{
		String fileName = getAutoGenIdFileName(testCaseName);
		JSONObject responseJson = null;
		FileOutputStream outputStrem = null;
		FileInputStream inputStrem = null;
		Properties props = new Properties();
		try {
			
			responseJson = new JSONObject(response.getBody().asString()).getJSONObject("response");
			inputStrem = new FileInputStream(getResourcePath()+fileName);
			props.load(inputStrem);
			String fieldNames[] = idKeyName.split(",");
			for (String filedName : fieldNames) {
				if(responseJson!=null && responseJson.has(filedName)) {
					String identifierKeyName = getAutogenIdKeyName(testCaseName, filedName);
					props.put(identifierKeyName, responseJson.get(filedName));
				}
				else {
					logger.error("Response doesn't contain autogenerated field: "+filedName+" to write- Response : "+response.asString());
				}
			}
			outputStrem = new FileOutputStream(getResourcePath()+fileName);
			props.store(outputStrem, "autogenerated fields");
			logger.info("added autogenerated fields to property: "+getResourcePath()+fileName);
		} catch (JSONException | IOException e) {
			logger.error("Exception while getting autogenerated id and writing in property file:" + e.getMessage());
		}

	}
	public void writeAutoGeneratedId(String testCaseName, String idName, String value)
	{
		if(testCaseName == null || idName == null || value == null)
			{
				logger.error("autogenerated id is not stored as few details not available");
				return ;
			}
			String fileName = getAutoGenIdFileName(testCaseName);
			String identifierKeyName = getAutogenIdKeyName(testCaseName, idName);
			FileOutputStream outputStream = null;
			FileInputStream inputStream = null;
			Properties props = new Properties();
			try {
				inputStream = new FileInputStream(getResourcePath()+fileName);
				props.load(inputStream);
				props.put(identifierKeyName, value);
				outputStream = new FileOutputStream(getResourcePath()+fileName);
				props.store(outputStream, "autogenerated fields");
				logger.info("added autogenerated fields to property: "+getResourcePath()+fileName);
			} catch (JSONException | IOException e) {
				logger.error("Exception while getting autogenerated id and writing in property file:" + e.getMessage());
			}
	}

	/**
	 * @param testCaseName
	 * @param fieldName
	 * @return testCaseName_fieldname
	 */
	public String getAutogenIdKeyName(String testCaseName, String fieldName)
	{
		if(testCaseName == null) return null;
		int indexof_= testCaseName.indexOf("_");
		String autogenIdKeyName = testCaseName.substring(indexof_+1);
		autogenIdKeyName = autogenIdKeyName+"_"+fieldName;
		logger.info("key for testCase: "+testCaseName+" : "+autogenIdKeyName);
		return autogenIdKeyName;
	}
	
	
	public static String getGlobalResourcePath() {
		return MosipTestRunner.getGlobalResourcePath();
	}
	
	public static String getResourcePath() {
		return getGlobalResourcePath()+"/"+resourceFolderName+"/";
	}
	
	public static void initiateAdminTest() {
		copyAdminTestResource();
	}
	
	public static void copyAdminTestResource() {
		try {
			File source = new File(getGlobalResourcePath() + "/admin");
			File destination = new File(getGlobalResourcePath() + "/"+RunConfigUtil.resourceFolderName);
			FileUtils.copyDirectoryToDirectory(source, destination);
			logger.info("Copied the admin test resource successfully");
		} catch (Exception e) {
			logger.error("Exception occured while copying the file: "+e.getMessage());
		}
	}
	public static void initiateKernelTest()
	{
		try {
			File source = new File(getGlobalResourcePath() + "/kernel");
			File destination = new File(getGlobalResourcePath() + "/"+RunConfigUtil.resourceFolderName);
			FileUtils.copyDirectoryToDirectory(source, destination);
			logger.info("Copied the kernel test resource successfully");
		} catch (Exception e) {
			logger.error("Exception occured while copying the file: "+e.getMessage());
		}
	}
	
	public static void initiateregProcTest()
	{
		try {
			File source = new File(RunConfigUtil.getGlobalResourcePath() + "/regProc");
			File destination = new File(RunConfigUtil.getGlobalResourcePath() + "/"+RunConfigUtil.resourceFolderName);
			FileUtils.copyDirectoryToDirectory(source, destination);
			logger.info("Copied the regProc test resource successfully");
		} catch (Exception e) {
			logger.error("Exception occured while copying the file: "+e.getMessage());
		}
	}
	
	public Object[] getYmlTestData(String ymlPath){
		String testType = testLevel;
		final ObjectMapper mapper = new ObjectMapper();
		List<TestCaseDTO> testCaseDTOList = new LinkedList<TestCaseDTO>();
		Map<String, Map<String, Map<String, String>>> scriptsMap = loadyaml(ymlPath);
		for (String key : scriptsMap.keySet()) {
			Map<String, Map<String, String>> testCases = scriptsMap.get(key);
			if(testType.equalsIgnoreCase("smoke")){
				testCases = testCases.entrySet().stream().filter(mapElement -> mapElement.getKey().toLowerCase().contains("smoke")).collect(Collectors.toMap(mapElement -> mapElement.getKey(), mapElement -> mapElement.getValue()));
			}
			for (String testCase : testCases.keySet()) {
				TestCaseDTO testCaseDTO = mapper.convertValue(testCases.get(testCase), TestCaseDTO.class);
						testCaseDTO.setTestCaseName(testCase);
						testCaseDTOList.add(testCaseDTO);
			}
		}
		return testCaseDTOList.toArray();
	}
	
	@SuppressWarnings("unchecked")
	protected Map<String,Map<String, Map<String, String>>> loadyaml(String path) {
		Map<String,Map<String, Map<String, String>>> scriptsMap = null;
		try {
			Yaml yaml = new Yaml();
			InputStream inputStream = new FileInputStream(
					new File(getResourcePath() + path).getAbsoluteFile());
		scriptsMap = (Map<String,Map<String, Map<String, String>>>) yaml.load(inputStream);
		} catch (Exception e) {
			logger.error(e.getMessage());
			return null;
		}
		return scriptsMap;
	}	
	
	public String getJsonFromTemplate(String input, String template)
	{
		String resultJson = null;
		try {
			Handlebars handlebars = new Handlebars();
			Gson gson = new Gson();
			Type type = new TypeToken<Map<String, Object>>(){}.getType();
			Map<String, Object> map = gson.fromJson(input, type);   
			String templateJsonString = new String(Files.readAllBytes(Paths.get(getResourcePath()+template+".hbs")), "UTF-8");
			Template compiledTemplate = handlebars.compileInline(templateJsonString);
			Context context = Context.newBuilder(map).build();
			resultJson = compiledTemplate.apply(context);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return resultJson;
	}

	String inputJsonKeyWordHandeler(String jsonString, String testCaseName)
	{
		if(jsonString==null)
		{
			logger.info(" Request Json String is :"+jsonString);
			return jsonString;
		}
		if(jsonString.contains("$TIMESTAMP$"))
			jsonString = jsonString.replace("$TIMESTAMP$", generateCurrentUTCTimeStamp());
		if(jsonString.contains("$TIMESTAMPL$"))
			jsonString = jsonString.replace("$TIMESTAMPL$", generateCurrentLocalTimeStamp());
		if(jsonString.contains("$REMOVE$")) 
			jsonString = removeObject(new JSONObject(jsonString));
		if(jsonString.contains("$ID:")) {
			String autoGenIdFileName = getAutoGenIdFileName(testCaseName);
			jsonString = replaceIdWithAutogeneratedId(jsonString, "$ID:", autoGenIdFileName);
		}
		return jsonString;
	}
	
	public String getAutoGenIdFileName(String testCaseName)
	{
		if(testCaseName == null) return null;
		if(testCaseName.toLowerCase().startsWith("admin"))
			return adminAutoGeneratedIdPropFileName;
		else if(testCaseName.toLowerCase().startsWith("prereg"))
			return preregAutoGeneratedIdPropFileName;
		else if(testCaseName.toLowerCase().startsWith("partner"))
			return partnerAutoGeneratedIdPropFileName;
		else if(testCaseName.toLowerCase().startsWith("idrepo"))
			return idrepoAutoGeneratedIdPropFileName;
		else if(testCaseName.toLowerCase().startsWith("resident"))
			return residentAutoGeneratedIdPropFileName;
		else if(testCaseName.toLowerCase().startsWith("regproc"))
			return regProcAutoGeneratedIdPropFileName;
		else if(testCaseName.toLowerCase().startsWith("auth"))
			return authAutoGeneratedIdPropFileName;
		return null;
	}
	
	public String getAutoGeneratedFieldValue(String inputFromYml, String testCaseName) {
		String autoGenIdFileName = getAutoGenIdFileName(testCaseName);
		if(!inputFromYml.contains("$ID:"))
			return "Input doesn't contain autogenerateIdKey";
		String keyForIdProperty = StringUtils.substringBetween(inputFromYml, "$ID:", "$");
		Properties props = new Properties();
			try {
				FileInputStream inputStrem = new FileInputStream(getResourcePath()+autoGenIdFileName);
				props.load(inputStrem);
			} catch (IOException e) {
				logger.error("Exception while loading the autogenerated id: "+e.getMessage());
			}
			String autoGeneratedFieldValue = props.getProperty(keyForIdProperty);
			return autoGeneratedFieldValue;
	}
	public String updateTimestampOtp(String otpIdentyEnryptRequest) {
		otpIdentyEnryptRequest = JsonPrecondtion.parseAndReturnJsonContent(otpIdentyEnryptRequest, generateCurrentUTCTimeStamp(), "identityRequest.timestamp");
		if(proxy)
			otpIdentyEnryptRequest = JsonPrecondtion.parseAndReturnJsonContent(otpIdentyEnryptRequest, props.getProperty("proxyOTP"), "identityRequest.otp");
		else return  otpIdentyEnryptRequest;
		
		return otpIdentyEnryptRequest;
	}
	public static String generateCurrentUTCTimeStamp() {
		Date date = new Date();
		SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
		dateFormat.setTimeZone(TimeZone.getTimeZone("UTC"));
		return dateFormat.format(date);
	}
	private String generateCurrentLocalTimeStamp()
	{
		Date date = new Date();
		SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
		return dateFormat.format(date);
	}
	private String replaceIdWithAutogeneratedId(String jsonString, String idKey, String autoGenIdFileName)
	{
		if(!jsonString.contains(idKey))
			return jsonString;
		else {
			String keyForIdProperty = StringUtils.substringBetween(jsonString, idKey, "$");
			String keyToReplace = idKey+keyForIdProperty+"$";
			Properties props = new Properties();
				try {
					FileInputStream inputStrem = new FileInputStream(getResourcePath()+autoGenIdFileName);
					props.load(inputStrem);
				} catch (IOException e) {
					logger.error("Exception while loading the autogenerated id: "+e.getMessage());
				}
				jsonString = jsonString.replace(keyToReplace, props.getProperty(keyForIdProperty));
				jsonString =replaceIdWithAutogeneratedId(jsonString, idKey, autoGenIdFileName);
		}
		return jsonString;
	}
	
	public String removeObject(JSONObject object) {
		Iterator<String> keysItr = object.keys();
		while (keysItr.hasNext()) {
			String key = keysItr.next();
			Object value = object.get(key);
			if (value instanceof JSONArray) {
				JSONArray array = (JSONArray) value;
				String finalarrayContent = "";
				if (array.length() != 0) {
					for (int i = 0; i < array.length(); ++i) {
						if (!array.toString().contains("{") && !array.toString().contains("}")) {
							Set<String> arr = new HashSet<String>();
							for (int k = 0; k < array.length(); k++) {
								arr.add(array.getString(k));
							}
							finalarrayContent = removObjectFromArray(arr);
						} else {
							String arrayContent = removeObject(new JSONObject(array.get(i).toString()),finalarrayContent);
							if (!arrayContent.equals("{}"))
								finalarrayContent = finalarrayContent + "," + arrayContent;
						}
					}
					finalarrayContent = finalarrayContent.substring(1, finalarrayContent.length());
					object.put(key, new JSONArray("[" + finalarrayContent + "]"));
				} else
					object.put(key, new JSONArray("[]"));

			} else if (value instanceof JSONObject) {
				String objectContent = removeObject(new JSONObject(value.toString()));
				object.put(key, new JSONObject(objectContent));
			}
			if (value.toString().equals("$REMOVE$")) {
				object.remove(key);
				keysItr = object.keys();
			}
		}
		return object.toString();
	}
	private String removeObject(JSONObject object, String tempArrayContent) {
		Iterator<String> keysItr = object.keys();
		while (keysItr.hasNext()) {
			String key = keysItr.next();
			Object value = object.get(key);
			if (value instanceof JSONArray) {
				JSONArray array = (JSONArray) value;
				for (int i = 0; i < array.length(); ++i) {
					String arrayContent = removeObject(new JSONObject(array.get(i).toString()));
					object.put(key, new JSONArray("[" + arrayContent + "]"));
				}
			} else if (value instanceof JSONObject) {
				String objectContent = removeObject(new JSONObject(value.toString()));
				object.put(key, new JSONObject(objectContent));
			}
			if (value.toString().equals("$REMOVE$")) {
				object.remove(key);
				keysItr = object.keys();
			}
		}
		return object.toString();
	}
	private String removObjectFromArray(Set<String> content) {
		String array = "[";
		for (String str : content) {
			if (!str.contains("$REMOVE$"))
				array = array + '"' + str + '"' + ",";
		}
		array = array.substring(0, array.length() - 1);
		array = array + "]";
		return array;
	}
	
	protected Response postWithOnlyPathParamAndCookie(String url, String jsonInput, String cookieName, String role, String testCaseName) {
		Response response=null;
		jsonInput = inputJsonKeyWordHandeler(jsonInput, testCaseName);
		HashMap<String, String> map = null;
		try {
			map = new Gson().fromJson(jsonInput, new TypeToken<HashMap<String, String>>(){}.getType());
		} catch (Exception e) {
			logger.error("Not able to convert jsonrequet to map: "+jsonInput+" Exception: "+e.getMessage());
		}
	
	token = kernelAuthLib.getTokenByRole(role);
	logger.info("******get request to EndPointUrl: " + url + " *******");
	Reporter.log("<pre>" + ReportUtil.getTextAreaJsonMsgHtml(jsonInput) + "</pre>");
	try {
		  response = RestClient.postRequestWithCookieAndOnlyPathParm(url, map, MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON, cookieName, token);
		  Reporter.log("<b><u>Actual Response Content: </u></b>(EndPointUrl: " + url + ") <pre>"
					+ ReportUtil.getTextAreaJsonMsgHtml(response.asString()) + "</pre>");
		return response;
	} catch (Exception e) {
		logger.error("Exception " + e);
		return response;
	}
}
	
	private static File updateCSV(String fileToUpdate, String replace,
		    int row, int col) {
		File inputFile = new File(fileToUpdate);
		List<String[]> csvBody;
		try {
			CSVReader reader = new CSVReader(new FileReader(inputFile), ',');
			csvBody = reader.readAll();
			csvBody.get(row)[col] = replace;
			reader.close();
			CSVWriter writer = new CSVWriter(new FileWriter(inputFile), ',');
			writer.writeAll(csvBody);
			writer.flush();
			writer.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
		return inputFile;
		}
	
	public static Properties getproperty(String path) {
		Properties prop = new Properties();
		
		try {
			File file = new File(path);
			prop.load(new FileInputStream(file));
		} catch (IOException e) {
			logger.error("Exception " + e.getMessage());
		}
		return prop;
	}
public String generateSignatureWithRequest(String Request, String payload) {
	
	
		String signUrl = ApplnURI+props.getProperty("internalSignEndpoint");
		String token = kernelAuthLib.getTokenByRole("regproc");
		String encodedrequest = Base64.getEncoder().encodeToString(Request.getBytes());
		String signJsonPath = MosipTestRunner.getGlobalResourcePath() + "/"+props.getProperty("signJsonPath");
		String reqJsonString = FileUtil.readInput(signJsonPath);
		if(payload != null)
		reqJsonString = JsonPrecondtion.parseAndReturnJsonContent(reqJsonString, payload, "request.includePayload");
		reqJsonString = reqJsonString.replace("$DATA$", encodedrequest);
		Response response=RestClient.postRequestWithCookie(signUrl, reqJsonString, MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON, COOKIENAME, token);
		JSONObject res = new JSONObject(response.asString());
		JSONObject responseJson = new JSONObject(res.get("response").toString());
		if(responseJson.has("jwtSignedData"))
		return responseJson.get("jwtSignedData").toString();
		else
			logger.error("No able to get the Signature from: "+signUrl+" with request: "+reqJsonString);
		return "Not able to Get Signature";
		
	}
	
/**
 * The method will modify json request with the given field values in map
 * 
 * @param listOfFiles
 * @param fieldvalue
 * @param propFileName
 * @param keywordinFile
 * @return true or false
 */
protected String modifyRequest(String inputJson, Map<String, String> fieldvalue, String propFileNameWithPath) {
	try {
				MessagePrecondtion jsonPrecon = new JsonPrecondtion();
				return jsonPrecon.parseAndUpdateJson(inputJson, fieldvalue, propFileNameWithPath);
		
	} catch (Exception e) {
		logger.error("Exception occured:" + e.getMessage());
		return inputJson;
	}
}

public static void copyPreregTestResource() {
	try {
		File source = new File(RunConfigUtil.getGlobalResourcePath() + "/preReg");
		File destination = new File(RunConfigUtil.getGlobalResourcePath() + "/"+RunConfigUtil.resourceFolderName);
		FileUtils.copyDirectoryToDirectory(source, destination);
		File config = new File(RunConfigUtil.getGlobalResourcePath() + "/config");
		FileUtils.copyDirectoryToDirectory(config, destination);
		logger.info("Copied the prereg test resource successfully");
	} catch (Exception e) {
		logger.error("Exception occured while copying the file: "+e.getMessage());
	}
}
public static void copyIdrepoTestResource() {
	try {
		File source = new File(RunConfigUtil.getGlobalResourcePath() + "/idRepository");
		File destination = new File(RunConfigUtil.getGlobalResourcePath() + "/"+RunConfigUtil.resourceFolderName);
		FileUtils.copyDirectoryToDirectory(source, destination);
		logger.info("Copied the idrepository test resource successfully");
	} catch (Exception e) {
		logger.error("Exception occured while copying the file: "+e.getMessage());
	}
}
public static void copyResidentTestResource() {
	try {
		File source = new File(RunConfigUtil.getGlobalResourcePath() + "/resident");
		File destination = new File(RunConfigUtil.getGlobalResourcePath() + "/"+RunConfigUtil.resourceFolderName);
		FileUtils.copyDirectoryToDirectory(source, destination);
		logger.info("Copied the Resident test resource successfully");
	} catch (Exception e) {
		logger.error("Exception occured while copying the file: "+e.getMessage());
	}
}
}
