modules:
  - name: admin-ui
    enabled: true
    image:
      registry: docker.io
      repository: mosipqa/uitest-admin
      tag: develop
      pullPolicy: Always
  - name: pmp-ui
    enabled: true
    image:
      registry: docker.io
      repository: mosipqa/uitest-pmp-v2
      tag: develop
      pullPolicy: Always
  - name: resident-ui
    enabled: true
    image:
      registry: docker.io
      repository: mosipqa/uitest-resident
      tag: develop
      pullPolicy: Always
  - name: verify-ui
    enabled: true
    image:
      registry: docker.io
      repository: mosipqa/uitest-verify
      tag: develop
  - name: injiweb-ui
    enabled: true
    image:
      registry: docker.io
      repository: mosipqa/uitest-web
      tag: develop
